# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
    'require.resolve(
                                        "react-native/scripts/react_native_pods.rb",
                                        {paths: [process.argv[1]]},
                                        )', __dir__]).strip

# Added by Ometria
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions(['Notifications'])


$RNFirebaseAsStaticFramework = true

pod 'GoogleUtilities', :modular_headers => true

def sharedConfig
  linkage = ENV['USE_FRAMEWORKS']
  if linkage != nil
    Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
    use_frameworks! :linkage => linkage.to_sym
  end

  use_frameworks! :linkage => :static
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseMessaging', :modular_headers => true
  pod 'ometria-react-native-sdk', :path => '../..', :modular_headers => true
end

target 'sampleAppTests' do
  inherit! :complete
  # Pods for testing
end

target 'sampleApp' do
  config = use_native_modules!
  sharedConfig
  use_react_native!(
                    :path => config[:reactNativePath],
                    # An absolute path to your application root.
                    :app_path => "#{Pod::Config.instance.installation_root}/.."
                    )
                    post_install do |installer|
                      # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
                      react_native_post_install(
                                                installer,
                                                config[:reactNativePath],
                                                :mac_catalyst_enabled => false,
                                                # :ccache_enabled => true
                                                )
                    end
end

target 'NotificationService' do
  use_frameworks! :linkage => :static
  pod 'Ometria'
end

