# Enable the new architecture
ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# <OmetriaSetup>
# Setup react-native-permissions
require_relative '../node_modules/react-native-permissions/scripts/setup'
# </OmetriaSetup>

platform :ios, min_ios_version_supported
prepare_react_native_project!

# <OmetriaSetup>
# Configure permissions for notifications
setup_permissions(['Notifications'])
# </OmetriaSetup>

# <OmetriaSetup>
# Firebase requires use_frameworks with static linkage
use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true
# </OmetriaSetup>

target 'sampleApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )

    # Add RCT_NEW_ARCH_ENABLED to preprocessor definitions for all targets
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_NEW_ARCH_ENABLED=1'
      end
    end
  end
end

# <OmetriaSetup>
# Notification Service Extension target
target 'NotificationsService' do
  use_frameworks! :linkage => :static
  pod 'Ometria', '~> 1.8.2'
end
# </OmetriaSetup>
