# Ometria TurboModule Setup for React Native New Architecture
#
# NOTE: This is a temporary workaround. We are actively working on a solution that
# will not require any manual Podfile changes. This script may be removed in a future
# version once automatic registration is implemented.
#
# WHY IS THIS NEEDED?
# -------------------
# React Native's New Architecture uses TurboModules, which require explicit registration
# in RCTModuleProviders.mm. This file is auto-generated by codegen during the build.
#
# The Ometria SDK is written in Swift, but TurboModule specs use C++ types that Swift
# cannot directly implement. To bridge this gap, we use an Objective-C++ wrapper class
# called `OmetriaReactNativeSdkTurboModule` that:
#   1. Implements the TurboModule spec (C++ compatible)
#   2. Forwards calls to the Swift implementation at runtime
#
# The problem: Codegen generates the spec interface but doesn't know about our custom
# wrapper class name. It generates an empty moduleMapping in RCTModuleProviders.mm.
# This script adds a build phase to patch that file during the ReactCodegen build.
#
# WHEN IS THIS NEEDED?
# --------------------
# Only when using the New Architecture (RCT_NEW_ARCH_ENABLED=1).
# The Old Architecture uses a different module discovery mechanism that works automatically.
#
# USAGE
# -----
# Add this to your Podfile:
#
#   require_relative '../node_modules/react-native-ometria/scripts/ometria_turbomodule'
#
#   post_install do |installer|
#     # ... other post_install code (like react_native_post_install) ...
#     patch_ometria_turbomodule(installer)
#   end
#

def patch_ometria_turbomodule(installer)
  # Only needed for New Architecture
  return unless ENV['RCT_NEW_ARCH_ENABLED'] == '1'

  installer.pods_project.targets.each do |target|
    next unless target.name == 'ReactCodegen'

    # Check if we already added the phase
    existing_phase = target.build_phases.find { |phase|
      phase.respond_to?(:name) && phase.name == '[Ometria] Patch TurboModule Registration'
    }

    if existing_phase
      Pod::UI.puts "[Ometria] TurboModule patch phase already exists"
      return
    end

    # Find the compile sources phase
    compile_phase = target.build_phases.find { |phase|
      phase.is_a?(Xcodeproj::Project::Object::PBXSourcesBuildPhase)
    }

    # Add our patch script to run before compile
    patch_script = target.new_shell_script_build_phase('[Ometria] Patch TurboModule Registration')
    patch_script.shell_script = <<~SCRIPT
      PROVIDERS_FILE="${PODS_ROOT}/../build/generated/ios/RCTModuleProviders.mm"
      if [ -f "$PROVIDERS_FILE" ]; then
        if ! grep -q "OmetriaReactNativeSdk" "$PROVIDERS_FILE"; then
          sed -i '' 's/moduleMapping = @{/moduleMapping = @{ @"OmetriaReactNativeSdk": @"OmetriaReactNativeSdkTurboModule",/' "$PROVIDERS_FILE"
          echo "[Ometria] Patched RCTModuleProviders.mm"
        else
          echo "[Ometria] Already patched"
        fi
      else
        echo "[Ometria] RCTModuleProviders.mm not found, skipping"
      fi
    SCRIPT

    # Move it before compile phase
    if compile_phase
      target.build_phases.move(patch_script, target.build_phases.index(compile_phase))
    end

    Pod::UI.puts "[Ometria] Added TurboModule patch to ReactCodegen build phases"
  end
end
