# Ometria TurboModule Setup for React Native New Architecture
#
# NOTE: This is a temporary workaround. We are actively working on a solution that
# will not require any manual Podfile changes. This script may be removed in a future
# version once automatic registration is implemented.
#
# WHY IS THIS NEEDED?
# -------------------
# React Native's New Architecture uses TurboModules, which require explicit registration
# in RCTModuleProviders.mm. This file is auto-generated by codegen during `pod install`.
#
# The Ometria SDK is written in Swift, but TurboModule specs use C++ types that Swift
# cannot directly implement. To bridge this gap, we use an Objective-C++ wrapper class
# called `OmetriaReactNativeSdkTurboModule` that:
#   1. Implements the TurboModule spec (C++ compatible)
#   2. Forwards calls to the Swift implementation at runtime
#
# The problem: Codegen generates the spec interface but doesn't know about our custom
# wrapper class name. It only generates an empty moduleMapping in RCTModuleProviders.mm.
# This script patches that file to register our wrapper class.
#
# WHEN IS THIS NEEDED?
# --------------------
# Only when using the New Architecture (RCT_NEW_ARCH_ENABLED=1).
# The Old Architecture uses a different module discovery mechanism that works automatically.
#
# USAGE
# -----
# Add this to your Podfile:
#
#   require_relative '../node_modules/react-native-ometria/scripts/ometria_turbomodule'
#
#   post_install do |installer|
#     # ... other post_install code (like react_native_post_install) ...
#     patch_ometria_turbomodule(installer)
#   end
#

def patch_ometria_turbomodule(installer)
  # Only needed for New Architecture
  return unless ENV['RCT_NEW_ARCH_ENABLED'] == '1'

  module_providers_path = "#{Pod::Config.instance.installation_root}/build/generated/ios/RCTModuleProviders.mm"

  unless File.exist?(module_providers_path)
    Pod::UI.warn "[Ometria] RCTModuleProviders.mm not found - skipping TurboModule patch"
    return
  end

  content = File.read(module_providers_path)

  # Check if already patched
  if content.include?('OmetriaReactNativeSdk')
    Pod::UI.puts "[Ometria] TurboModule already registered in RCTModuleProviders.mm"
    return
  end

  # Add the module mapping entry
  patched = content.gsub(
    /moduleMapping = @\{\s*/,
    "moduleMapping = @{\n      @\"OmetriaReactNativeSdk\": @\"OmetriaReactNativeSdkTurboModule\",\n      "
  )

  File.write(module_providers_path, patched)
  Pod::UI.puts "[Ometria] Successfully registered TurboModule in RCTModuleProviders.mm"
end
